# Generated by Django 3.2.8 on 2021-11-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('taken', models.BooleanField()),
                ('url', models.URLField(max_length=300)),
            ],
        ),
    ]
